<Project>

  <PropertyGroup>
    <InternalGeneratorsPackageId>XmlDocFormat.InternalGenerators</InternalGeneratorsPackageId>
    <InternalGeneratorsVersion>0.3.1</InternalGeneratorsVersion>

    <InternalGeneratorsLocation>$(SolutionDir)artifacts/generators/</InternalGeneratorsLocation>
    <InternalGeneratorsBuiltPackageLocation>
      $(InternalGeneratorsLocation)$(InternalGeneratorsPackageId).$(InternalGeneratorsVersion).nupkg
    </InternalGeneratorsBuiltPackageLocation>

    <InternalGeneratorsProjectLocation>
      $(SolutionDir)tools/XmlDocFormat.InternalGenerators/XmlDocFormat.InternalGenerators.csproj
    </InternalGeneratorsProjectLocation>
  </PropertyGroup>

</Project>
