<Project>

  <PropertyGroup>
    <InternalGeneratorsPackageId>XmlDocFormat.InternalGenerators</InternalGeneratorsPackageId>
    <InternalGeneratorsVersion>0.2.0</InternalGeneratorsVersion>

    <InternalGeneratorsLocation>$(SolutionDir)artifacts/generators/</InternalGeneratorsLocation>
  </PropertyGroup>

  <Target
    Name="EnsureLocalNuGetLocationsExist"
    BeforeTargets="PrepareForBuild">

    <MakeDir
      Directories="$(InternalGeneratorsLocation)"
      Condition="!Exists('$(InternalGeneratorsLocation)')" />

  </Target>

</Project>
