using Garyon.Functions;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using XmlDocFormat.InternalGenerators.Core;

namespace XmlDocFormat.InternalGenerators;

[Generator]
public sealed class  ConstructFromImplicitCastGenerator : IIncrementalGenerator
{
    private static readonly string ConstructFromImplicitCastAttributeTypeName
        = typeof(ConstructFromImplicitCastAttribute).ToString();

    private static readonly string ConstructFromImplicitCastGeneratorTypeName
        = typeof(ConstructFromImplicitCastGenerator).ToString();

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ConstructFromImplicitCastAttributeTypeName,
                Filter,
                FindAffectedType)
            .Where(Predicates.NotNull)
            .Select(GetTypeImplicitCastableConstructorGroup!)
            ;

        context.RegisterSourceOutput(provider, GenerateSource);
    }

    private void GenerateSource(
        SourceProductionContext context,
        ImplicitCastableConstructorGroup data)
    {
        var writer = new Writer();
        writer.AppendHeaderText();

        using (writer.AppendPartialType(data.TargetType))
        {
            foreach (var constructor in data.Constructors)
            {
                writer.GenerateFactoryMethod(constructor);
            }
        }

        var result = writer.ToString();
        context.AddSource($"{data.TargetType.ToDisplayString()}.ConstructFromImplicitCastMethods.g.cs", result);
    }

    private ImplicitCastableConstructorGroup GetTypeImplicitCastableConstructorGroup(
        INamedTypeSymbol targetType,
        CancellationToken cancellationToken)
    {
        var eligibleConstructors = targetType.InstanceConstructors
            .Where(IsTargetEligibleConstructor)
            .ToImmutableArray();
        if (HasFactoryAttribute(targetType))
        {
            return new(targetType, eligibleConstructors);
        }

        var filteredConstructors = eligibleConstructors
            .Where(HasFactoryAttribute)
            .ToImmutableArray();

        return new(targetType, filteredConstructors);

        static bool HasFactoryAttribute(ISymbol symbol)
        {
            return symbol.GetAttributes().Any(IsFactoryAttribute);
        }

        static bool IsFactoryAttribute(AttributeData s)
        {
            return s.AttributeClass?.ToDisplayString() == ConstructFromImplicitCastAttributeTypeName;
        }

        bool IsTargetEligibleConstructor(
            IMethodSymbol method)
        {
            return IsEligibleConstructor(targetType, method);
        }
    }

    private static bool IsEligibleConstructor(
        INamedTypeSymbol targetType,
        IMethodSymbol method)
    {
        return method.Parameters is [var single]
            && single.Type.TypeKind is not TypeKind.Interface
            && !single.Type.Equals(targetType, SymbolEqualityComparer.Default)
            ;
    }

    private INamedTypeSymbol? FindAffectedType(
        GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        var target = context.TargetSymbol;
        if (target is IMethodSymbol { MethodKind: MethodKind.Constructor } method)
        {
            return method.ContainingType;
        }

        if (target is INamedTypeSymbol namedType)
        {
            return namedType;
        }

        return null;
    }

    private static bool Filter(SyntaxNode node, CancellationToken token)
    {
        return true;
    }

    private sealed record ImplicitCastableConstructorGroup(
        INamedTypeSymbol TargetType,
        ImmutableArray<IMethodSymbol> Constructors)
    {
    }

    private sealed class Writer : CSharpCodeBuilder
    {
        public Writer()
            : base(' ', 4)
        {
        }

        public void AppendHeaderText()
        {
            var header = $$"""
                // <auto-generated>
                //     This file has been auto-generated by
                //     {{ConstructFromImplicitCastGeneratorTypeName}}
                // </auto-generated>
                
                #nullable enable
                

                """;

            AppendLine(header);
        }

        public void GenerateFactoryMethod(IMethodSymbol constructor)
        {
            GoodAssert.True(constructor.IsStatic is false);
            GoodAssert.True(constructor.MethodKind is MethodKind.Constructor);
            var parameters = constructor.Parameters;
            GoodAssert.True(parameters.Length is 1);

            var parameter = parameters[0];
            var isNullableParameter = parameter.Type.NullableAnnotation is NullableAnnotation.Annotated;
            var allowsNullReturn = !isNullableParameter;
            var parameterName = parameter.Name;

            SeparateBlock();

            if (allowsNullReturn)
            {
                Append("[return: ");
                Append($"global::{typeof(NotNullIfNotNullAttribute).FullName}");
                AppendLine($"(nameof({parameterName}))]");
            }

            WriteAccessibility(constructor);
            Append(" static implicit operator ");
            var qualifiedName = FullyQualifiedName(constructor.ContainingType);
            Append(qualifiedName);
            if (allowsNullReturn)
            {
                Append('?');
            }

            var parameterQualifiedName = FullyQualifiedName(parameter.Type);
            AppendLine($"({parameterQualifiedName}? {parameter.Name})");

            Append("    => ");
            if (allowsNullReturn)
            {
                Append($"{parameter.Name} is null ? null : ");
            }
            AppendLine($"new({parameter.Name});");

            CommitBlock();
        }
    }
}
