using Garyon.Extensions;
using Garyon.Functions;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using XmlDocFormat.InternalGenerators.Core;

namespace XmlDocFormat.InternalGenerators;

[Generator]
public sealed class ConstructFromImplicitCastGenerator : IIncrementalGenerator
{
    private static readonly string ConstructFromImplicitCastAttributeTypeName
        = typeof(ConstructFromImplicitCastAttribute).ToString();

    private static readonly string ConstructFromImplicitCastGeneratorTypeName
        = typeof(ConstructFromImplicitCastGenerator).ToString();

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ConstructFromImplicitCastAttributeTypeName,
                Filter,
                FindAffectedType)
            .Where(Predicates.NotNull)
            .Select(GetTypeImplicitCastableConstructorGroup!)
            ;

        context.RegisterSourceOutput(provider, GenerateSource);
    }

    private void GenerateSource(
        SourceProductionContext context,
        ImplicitCastableConstructorGroup data)
    {
        if (data.Constructors is [])
        {
            return;
        }

        var result = ProduceSource(data);
        var hintName = GeneratorHelpers.GeneratedHintNameForType(
            data.TargetType.Symbol, "ConstructFromImplicitCastMethods");
        context.AddSource(hintName, result);
    }

    private static string ProduceSource(
        ImplicitCastableConstructorGroup data)
    {
        var builder = new SourceBuilder(data);
        return builder.BuildFile();
    }

    private ImplicitCastableConstructorGroup GetTypeImplicitCastableConstructorGroup(
        CompilationWrappedSymbol<INamedTypeSymbol> targetType,
        CancellationToken cancellationToken)
    {
        var targetTypeSymbol = targetType.Symbol;
        var eligibleConstructors = targetTypeSymbol.InstanceConstructors
            .Where(IsTargetEligibleConstructor)
            .ToImmutableArray();
        if (HasFactoryAttribute(targetTypeSymbol))
        {
            return new(targetType, eligibleConstructors);
        }

        var filteredConstructors = eligibleConstructors
            .Where(HasFactoryAttribute)
            .ToImmutableArray();

        return new(targetType, filteredConstructors);

        static bool HasFactoryAttribute(ISymbol symbol)
        {
            return symbol.GetAttributes().Any(IsFactoryAttribute);
        }

        static bool IsFactoryAttribute(AttributeData s)
        {
            return s.AttributeClass?.ToDisplayString() == ConstructFromImplicitCastAttributeTypeName;
        }

        bool IsTargetEligibleConstructor(
            IMethodSymbol method)
        {
            return IsEligibleConstructor(targetTypeSymbol, method);
        }
    }

    private static bool IsEligibleConstructor(
        INamedTypeSymbol targetType,
        IMethodSymbol method)
    {
        return method.Parameters is [var single]
            && single.Type.TypeKind is not TypeKind.Interface
            && !single.Type.Equals(targetType, SymbolEqualityComparer.Default)
            ;
    }

    private CompilationWrappedSymbol<INamedTypeSymbol>? FindAffectedType(
        GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        var compilation = context.SemanticModel.Compilation;
        var target = context.TargetSymbol;
        if (target is IMethodSymbol { MethodKind: MethodKind.Constructor } method)
        {
            return new(compilation, method.ContainingType);
        }

        if (target is INamedTypeSymbol namedType)
        {
            return new(compilation, namedType);
        }

        return null;
    }

    private static bool Filter(SyntaxNode node, CancellationToken token)
    {
        return true;
    }

    private sealed record ImplicitCastableConstructorGroup(
        CompilationWrappedSymbol<INamedTypeSymbol> TargetType,
        ImmutableArray<IMethodSymbol> Constructors)
    {
        public Compilation Compilation => TargetType.Compilation;
    }

    private sealed class SourceBuilder(ImplicitCastableConstructorGroup data)
        : CSharpSourceFileBuilder<CSharpCodeWriter>
    {
        protected override CSharpCodeWriter CreateCodeBuilder() => new();

        protected override string? GetHeader()
        {
            return $$"""
                // <auto-generated>
                //     This file has been auto-generated by
                //     {{ConstructFromImplicitCastGeneratorTypeName}}
                // </auto-generated>
                
                #nullable enable

                """;
        }

        protected override string? GetFooter() => null;

        protected override void BuildContent()
        {
            using (MainContentWriter.AppendPartialType(data.TargetType.Symbol))
            {
                foreach (var constructor in data.Constructors)
                {
                    GenerateFactoryMethod(constructor);
                }
            }
        }

        private void GenerateFactoryMethod(IMethodSymbol constructor)
        {
            GoodAssert.True(constructor.IsStatic is false);
            GoodAssert.True(constructor.MethodKind is MethodKind.Constructor);
            var parameters = constructor.Parameters;
            GoodAssert.True(parameters.Length is 1);

            var writer = MainContentWriter;

            var parameter = parameters[0];
            var isNullableParameter = parameter.Type.NullableAnnotation is NullableAnnotation.Annotated;
            var allowsNullReturn = !isNullableParameter;
            var parameterName = parameter.Name;

            writer.BeginNewBlock();

            if (allowsNullReturn)
            {
                writer.Append("[return: ");
                writer.Append($"global::{typeof(NotNullIfNotNullAttribute).FullName}");
                writer.AppendLine($"(nameof({parameterName}))]");
            }

            writer.WriteAccessibility(constructor);
            writer.Append(" static implicit operator ");
            var qualifiedName = FullyQualifiedNameOrKeyword(
                constructor.ContainingType,
                data.Compilation);
            writer.Append(qualifiedName);
            if (allowsNullReturn)
            {
                writer.Append('?');
            }

            var parameterQualifiedName = FullyQualifiedNameOrKeyword(
                parameter.Type,
                data.Compilation);
            writer.AppendLine($"({parameterQualifiedName}? {parameter.Name})");

            writer.Append("    => ");
            if (allowsNullReturn)
            {
                writer.Append($"{parameter.Name} is null ? null : ");
            }

            var nullableUnwrap = parameter.Type.IsNullableStruct()
                .SwitchValue(".Value", string.Empty);
            writer.AppendLine($"new({parameter.Name}{nullableUnwrap});");

            writer.CommitBlock();
        }
    }
}
