using Garyon.Functions;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using XmlDocFormat.InternalGenerators.Core;

namespace XmlDocFormat.InternalGenerators;

[Generator]
public sealed class FactoryConstructorGenerator : IIncrementalGenerator
{
    private static readonly string FactoryConstructorAttributeTypeName
        = typeof(FactoryConstructorAttribute).ToString();

    private static readonly string FactoryConstructorGeneratorTypeName
        = typeof(FactoryConstructorGenerator).ToString();

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                FactoryConstructorAttributeTypeName,
                Filter,
                FindAffectedType)
            .Where(Predicates.NotNull)
            .Select(GetTypeFactoryConstructorGroup!)
            ;

        context.RegisterSourceOutput(provider, GenerateSource);
    }

    private void GenerateSource(
        SourceProductionContext context,
        TypeFactoryConstructorGroup data)
    {
        var writer = new Writer();
        writer.AppendHeaderText();

        using (writer.AppendPartialType(data.TargetType))
        {
            foreach (var constructor in data.Constructors)
            {
                writer.GenerateFactoryMethod(constructor);
            }
        }

        var result = writer.ToString();
        context.AddSource($"{data.TargetType.ToDisplayString()}.ConstructorFactoryMethods.g.cs", result);
    }

    private TypeFactoryConstructorGroup GetTypeFactoryConstructorGroup(
        INamedTypeSymbol targetType,
        CancellationToken cancellationToken)
    {
        var allConstructors = targetType.InstanceConstructors;
        if (HasFactoryAttribute(targetType))
        {
            return new(targetType, allConstructors);
        }

        var filteredConstructors = allConstructors
            .Where(HasFactoryAttribute)
            .ToImmutableArray();

        return new(targetType, filteredConstructors);

        static bool HasFactoryAttribute(ISymbol symbol)
        {
            return symbol.GetAttributes().Any(IsFactoryAttribute);
        }

        static bool IsFactoryAttribute(AttributeData s)
        {
            return s.AttributeClass?.ToDisplayString() == FactoryConstructorAttributeTypeName;
        }
    }

    private INamedTypeSymbol? FindAffectedType(
        GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        var target = context.TargetSymbol;
        if (target is IMethodSymbol { MethodKind: MethodKind.Constructor } method)
        {
            return method.ContainingType;
        }

        if (target is INamedTypeSymbol namedType)
        {
            return namedType;
        }

        return null;
    }

    private static bool Filter(SyntaxNode node, CancellationToken token)
    {
        return true;
    }

    private sealed record TypeFactoryConstructorGroup(
        INamedTypeSymbol TargetType,
        ImmutableArray<IMethodSymbol> Constructors)
    {
    }

    private sealed class Writer : CSharpCodeBuilder
    {
        public void AppendHeaderText()
        {
            var header = $$"""
                // <auto-generated>
                //     This file has been auto-generated by
                //     {{FactoryConstructorGeneratorTypeName}}
                // </auto-generated>

                #nullable enable


                """;

            AppendLine(header);
        }

        public void GenerateFactoryMethod(IMethodSymbol constructor)
        {
            const string factoryMethodName = "New";

            GoodAssert.True(constructor.IsStatic is false);
            GoodAssert.True(constructor.MethodKind is MethodKind.Constructor);

            var parameters = constructor.Parameters;

            SeparateBlock();

            WriteAccessibility(constructor);
            Append(" static ");
            var qualifiedName = FullyQualifiedName(constructor.ContainingType);
            Append(qualifiedName);
            Append($" {factoryMethodName}(");
            WriteParameterList(parameters);
            Append(") => new(");
            WriteCommaSeparatedList(parameters.Select(ParameterPassExpression));
            AppendLine(");");

            CommitBlock();
        }
    }
}
