using Garyon.Functions;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using XmlDocFormat.InternalGenerators.Core;

namespace XmlDocFormat.InternalGenerators;

[Generator]
public sealed class FactoryConstructorGenerator : IIncrementalGenerator
{
    private static readonly string FactoryConstructorAttributeTypeName
        = typeof(FactoryConstructorAttribute).ToString();

    private static readonly string FactoryConstructorGeneratorTypeName
        = typeof(FactoryConstructorGenerator).ToString();

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                FactoryConstructorAttributeTypeName,
                Filter,
                FindAffectedType)
            .Where(Predicates.NotNull)
            .Select(GetTypeFactoryConstructorGroup!)
            ;

        context.RegisterSourceOutput(provider, GenerateSource);
    }

    private void GenerateSource(
        SourceProductionContext context,
        TypeFactoryConstructorGroup data)
    {
        var result = ProduceSource(data);
        var hintName = GeneratorHelpers.GeneratedHintNameForType(
            data.TargetType.Symbol, "ConstructorFactoryMethods");
        context.AddSource(hintName, result);
    }

    private static string ProduceSource(
        TypeFactoryConstructorGroup data)
    {
        var builder = new SourceBuilder(data);
        return builder.BuildFile();
    }

    private TypeFactoryConstructorGroup GetTypeFactoryConstructorGroup(
        CompilationWrappedSymbol<INamedTypeSymbol> targetType,
        CancellationToken cancellationToken)
    {
        var targetTypeSymbol = targetType.Symbol;
        var allConstructors = targetTypeSymbol.InstanceConstructors;
        if (HasFactoryAttribute(targetTypeSymbol))
        {
            return new(targetType, allConstructors);
        }

        var filteredConstructors = allConstructors
            .Where(HasFactoryAttribute)
            .ToImmutableArray();

        return new(targetType, filteredConstructors);

        static bool HasFactoryAttribute(ISymbol symbol)
        {
            return symbol.GetAttributes().Any(IsFactoryAttribute);
        }

        static bool IsFactoryAttribute(AttributeData s)
        {
            return s.AttributeClass?.ToDisplayString() == FactoryConstructorAttributeTypeName;
        }
    }

    private CompilationWrappedSymbol<INamedTypeSymbol>? FindAffectedType(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var compilation = context.SemanticModel.Compilation;
        var target = context.TargetSymbol;
        if (target is IMethodSymbol { MethodKind: MethodKind.Constructor } method)
        {
            return new(compilation, method.ContainingType);
        }

        if (target is INamedTypeSymbol namedType)
        {
            return new(compilation, namedType);
        }

        return null;
    }

    private static bool Filter(SyntaxNode node, CancellationToken token)
    {
        return true;
    }

    private sealed record TypeFactoryConstructorGroup(
        CompilationWrappedSymbol<INamedTypeSymbol> TargetType,
        ImmutableArray<IMethodSymbol> Constructors)
    {
        public Compilation Compilation => TargetType.Compilation;
    }

    private sealed class SourceBuilder(TypeFactoryConstructorGroup data)
        : CSharpSourceFileBuilder<CSharpCodeWriter>
    {
        protected override CSharpCodeWriter CreateCodeBuilder() => new();

        protected override string? GetHeader()
        {
            return $$"""
                // <auto-generated>
                //     This file has been auto-generated by
                //     {{FactoryConstructorGeneratorTypeName}}
                // </auto-generated>

                #nullable enable

                """;
        }

        protected override string? GetFooter() => null;

        protected override void BuildContent()
        {
            using (MainContentWriter.AppendPartialType(data.TargetType.Symbol))
            {
                foreach (var constructor in data.Constructors)
                {
                    GenerateFactoryMethod(constructor);
                }
            }
        }

        private void GenerateFactoryMethod(IMethodSymbol constructor)
        {
            const string factoryMethodName = "New";

            GoodAssert.True(constructor.IsStatic is false);
            GoodAssert.True(constructor.MethodKind is MethodKind.Constructor);

            var writer = MainContentWriter;

            var parameters = constructor.Parameters;

            writer.BeginNewBlock();

            writer.WriteAccessibility(constructor);
            writer.Append(" static ");

            var qualifiedName = FullyQualifiedName(
                constructor.ContainingType,
                data.Compilation);

            writer.Append(qualifiedName);
            writer.Append($" {factoryMethodName}(");
            writer.WriteParameterList(parameters);
            writer.Append(") => new(");
            writer.WriteCommaSeparatedList(
                parameters.Select(
                    CSharpCodeWriter.ParameterPassExpression));
            writer.AppendLine(");");

            writer.CommitBlock();
        }
    }
}
