using RoseLynn.Generators;
using XmlDocFormat.InternalGenerators.Tests.Testing;

namespace XmlDocFormat.InternalGenerators.Tests;

public sealed class ConstructFromImplicitCastGeneratorTests
    : BaseGeneratorTestContainer<ConstructFromImplicitCastGenerator>
{
    [Test]
    public async Task BasicTest(CancellationToken cancellationToken)
    {
        const string source =
            //lang=C#-test
            """
            using XmlDocFormat.InternalGenerators.Core;

            namespace XmlDocFormat.Core.Internals;

            [ConstructFromImplicitCast]
            public sealed partial class ValueWrapper(string value);
            """;

        var mappings = new GeneratedSourceMappings
        {
            ["XmlDocFormat.Core.Internals.ValueWrapper.ConstructFromImplicitCastMethods.g.cs"] =
                Utf8CSharpSource(
                    """
                    // <auto-generated>
                    //     This file has been auto-generated by
                    //     XmlDocFormat.InternalGenerators.ConstructFromImplicitCastGenerator
                    // </auto-generated>
                    
                    #nullable enable
                    
                    namespace XmlDocFormat.Core.Internals;
                    
                    partial class ValueWrapper
                    {
                        [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute(nameof(value))]
                        public static implicit operator global::XmlDocFormat.Core.Internals.ValueWrapper?(string? value)
                            => value is null ? null : new(value);
                    }
       
                    """),
        };

        await VerifyAsync(source, mappings, cancellationToken);
    }
}
