using RoseLynn.Generators;
using XmlDocFormat.InternalGenerators.Tests.Testing;

namespace XmlDocFormat.InternalGenerators.Tests;

// TODO: Test individual constructors

public sealed class ConstructFromImplicitCastGeneratorTests
    : BaseGeneratorTestContainer<ConstructFromImplicitCastGenerator>
{
    [Test]
    public async Task BasicTest(CancellationToken cancellationToken)
    {
        const string source =
            //lang=C#-test
            """
            using XmlDocFormat.InternalGenerators.Core;

            namespace XmlDocFormat.Core.Internals;

            [ConstructFromImplicitCast]
            public sealed partial class ValueWrapper(string value);
            """;

        var mappings = new GeneratedSourceMappings
        {
            ["XmlDocFormat.Core.Internals.ValueWrapper.ConstructFromImplicitCastMethods.g.cs"] =
                Utf8CSharpSource(
                    """
                    // <auto-generated>
                    //     This file has been auto-generated by
                    //     XmlDocFormat.InternalGenerators.ConstructFromImplicitCastGenerator
                    // </auto-generated>
                    
                    #nullable enable
                    
                    namespace XmlDocFormat.Core.Internals;
                    
                    partial class ValueWrapper
                    {
                        [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute(nameof(value))]
                        public static implicit operator global::XmlDocFormat.Core.Internals.ValueWrapper?(string? value)
                            => value is null ? null : new(value);
                    }
       
                    """),
        };

        await VerifyOrWriteExpectationAsync(source, mappings, cancellationToken);
    }

    [Test]
    public async Task GenericTest(CancellationToken cancellationToken)
    {
        const string source =
            //lang=C#-test
            """
            using XmlDocFormat.InternalGenerators.Core;

            namespace XmlDocFormat.Core.Internals;

            [ConstructFromImplicitCast]
            public sealed partial class ValueWrapper<T>(T value);
            """;

        var mappings = new GeneratedSourceMappings
        {
            ["XmlDocFormat.Core.Internals.ValueWrapper`1.ConstructFromImplicitCastMethods.g.cs"] =
                Utf8CSharpSource(
                    """
                    // <auto-generated>
                    //     This file has been auto-generated by
                    //     XmlDocFormat.InternalGenerators.ConstructFromImplicitCastGenerator
                    // </auto-generated>

                    #nullable enable

                    namespace XmlDocFormat.Core.Internals;

                    partial class ValueWrapper<T>
                    {
                        [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute(nameof(value))]
                        public static implicit operator global::XmlDocFormat.Core.Internals.ValueWrapper<T>?(T? value)
                            => value is null ? null : new(value);
                    }

                    """),
        };

        await VerifyOrWriteExpectationAsync(source, mappings, cancellationToken);
    }

    [Test]
    public async Task GenericWhereStructTest(CancellationToken cancellationToken)
    {
        const string source =
            //lang=C#-test
            """
            using XmlDocFormat.InternalGenerators.Core;

            namespace XmlDocFormat.Core.Internals;

            [ConstructFromImplicitCast]
            public sealed partial class ValueWrapper<T>(T value)
                where T : struct;
            """;

        var mappings = new GeneratedSourceMappings
        {
            ["XmlDocFormat.Core.Internals.ValueWrapper`1.ConstructFromImplicitCastMethods.g.cs"] =
                Utf8CSharpSource(
                    """
                    // <auto-generated>
                    //     This file has been auto-generated by
                    //     XmlDocFormat.InternalGenerators.ConstructFromImplicitCastGenerator
                    // </auto-generated>
                    
                    #nullable enable
                    
                    namespace XmlDocFormat.Core.Internals;
                    
                    partial class ValueWrapper<T>
                    {
                        [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute(nameof(value))]
                        public static implicit operator global::XmlDocFormat.Core.Internals.ValueWrapper<T>?(T? value)
                            => value is null ? null : new(value.Value);
                    }
       
                    """),
        };

        await VerifyOrWriteExpectationAsync(source, mappings, cancellationToken);
    }

    [Test]
    public async Task InterfaceTest(CancellationToken cancellationToken)
    {
        const string source =
            //lang=C#-test
            """
            using System;
            using XmlDocFormat.InternalGenerators.Core;

            namespace XmlDocFormat.Core.Internals;

            [ConstructFromImplicitCast]
            public sealed partial class DisposableWrapper(IDisposable value);
            """;

        var mappings = new GeneratedSourceMappings();

        await VerifyOrWriteExpectationAsync(source, mappings, cancellationToken);
    }

    [Test]
    public async Task ParameterlessConstructorTest(CancellationToken cancellationToken)
    {
        const string source =
            //lang=C#-test
            """
            using XmlDocFormat.InternalGenerators.Core;

            namespace XmlDocFormat.Core.Internals;

            [ConstructFromImplicitCast]
            public sealed partial class WithParameterlessConstructor();
            """;

        var mappings = new GeneratedSourceMappings();

        await VerifyOrWriteExpectationAsync(source, mappings, cancellationToken);
    }

    [Test]
    public async Task MultiParameterConstructorTest(CancellationToken cancellationToken)
    {
        const string source =
            //lang=C#-test
            """
            using XmlDocFormat.InternalGenerators.Core;

            namespace XmlDocFormat.Core.Internals;

            [ConstructFromImplicitCast]
            public sealed partial class KeyValuePairWrapper(string Key, string Value);
            """;

        var mappings = new GeneratedSourceMappings();

        await VerifyOrWriteExpectationAsync(source, mappings, cancellationToken);
    }
}
