using RoseLynn.Generators;
using XmlDocFormat.InternalGenerators.Tests.Testing;

namespace XmlDocFormat.InternalGenerators.Tests;

public sealed class FactoryConstructorGeneratorTests
    : BaseGeneratorTestContainer<FactoryConstructorGenerator>
{
    [Test]
    public async Task BasicTest(CancellationToken cancellationToken)
    {
        const string source =
            //lang=C#-test
            """
            using XmlDocFormat.InternalGenerators.Core;

            namespace XmlDocFormat.Core.Internals;

            [FactoryConstructor]
            public sealed partial class ValueWrapper(string value);
            """;

        var mappings = new GeneratedSourceMappings
        {
            ["XmlDocFormat.Core.Internals.ValueWrapper.ConstructorFactoryMethods.g.cs"] =
                Utf8CSharpSource(
                    """
                    // <auto-generated>
                    //     This file has been auto-generated by
                    //     XmlDocFormat.InternalGenerators.FactoryConstructorGenerator
                    // </auto-generated>

                    #nullable enable

                    namespace XmlDocFormat.Core.Internals;

                    partial class ValueWrapper
                    {
                        public static global::XmlDocFormat.Core.Internals.ValueWrapper New(string value) => new(value);
                    }

                    """),
        };

        await VerifyOrWriteExpectationAsync(source, mappings, cancellationToken);
    }
}
