using Garyon.Extensions;
using Microsoft.CodeAnalysis.Text;
using RoseLynn.Generators;
using XmlDocFormat.Core;
using XmlDocFormat.InternalGenerators.Tests.Testing;

namespace XmlDocFormat.InternalGenerators.Tests;

public class GeneratorOutputWriter : CSharpCodeWriter
{
    public static string GenerateSourceMappingsCode(GeneratedSourceMappings mappings)
    {
        var outputWriter = new GeneratorOutputWriter();
        outputWriter.AppendHeaderText();
        outputWriter.WriteSourceMappings(mappings);
        return outputWriter.ToString();
    }

    public void AppendHeaderText()
    {
        var header = $$"""
            // <auto-generated>
            //     This file has been auto-generated by
            //     {{nameof(GeneratorOutputWriter)}}
            // </auto-generated>

            // The purpose of this file is to show the output of a generator
            // run and construct the generator output expectation in RoseLynn's
            // fasion with GeneratedSourceMappings. The following code might
            // not be perfectly applicable without modifications depending on
            // the test project's structure.
            // The file has been constructed as a file-based program that does
            // not run any actual code, and only expresses the expected
            // generator output.

            #nullable enable


            """;

        AppendLine(header);
    }

    public void WriteSourceMappings(GeneratedSourceMappings mappings)
    {
        const string mappingsClassName = nameof(GeneratedSourceMappings);
        const string utf8CSharpSourceName = nameof(BaseGeneratorTestContainer<>.Utf8CSharpSource);

        CommitSingleLineContent($"var mappings = new {mappingsClassName}");
        CommitSingleLineContent("{");

        using (IncrementNestingLevel())
        {
            var blockList = NewSeparatableBlockList();
            foreach (var mapping in mappings)
            {
                blockList.BeginNewBlock();
                WriteMapping(mapping);
                blockList.CommitBlock();
            }
        }

        CommitSingleLineContent("};");

        void WriteMapping(KeyValuePair<string, SourceText> mapping)
        {
            CommitSingleLineContent($"""["{mapping.Key}"] =""");
            using (IncrementNestingLevel())
            {
                CommitSingleLineContent($"{utf8CSharpSourceName}(");
                using (IncrementNestingLevel())
                {
                    var source = mapping.Value.ToString();
                    var delimiter = GetRawStringDelimiters(source);
                    CommitSingleLineContent(delimiter);
                    AppendLine(source);
                    // Dentextist bug where the text's final new line is not consumed
                    if (source.EndsWith('\n'))
                    {
                        AppendLine();
                    }
                    CommitSingleLineContent($"{delimiter}),");
                }
            }
        }
    }

    private static string GetRawStringDelimiters(string content)
    {
        const char quote = '"';
        const int minDelimiterLength = 3;
        var largestQuoteSequence = LargestSequenceOf(content, quote);
        var delimiterLength = Math.Max(largestQuoteSequence, minDelimiterLength);
        return new RepeatedChar(quote, delimiterLength).ToString();
    }

    private static int LargestSequenceOf(string content, char target)
    {
        int largest = 0;
        int currentSequence = 0;

        foreach (var contentChar in content)
        {
            if (contentChar == target)
            {
                currentSequence++;
            }
            else
            {
                ConsumeLargest();
            }
        }

        ConsumeLargest();
        return largest;

        void ConsumeLargest()
        {
            largest.AssignMax(currentSequence);
            currentSequence = 0;
        }
    }
}
