using Garyon.Objects.Strings;
using RoseLynn.Generators;
using System.Diagnostics.CodeAnalysis;
using XmlDocFormat.Core;
using XmlDocFormat.InternalGenerators.Tests.Testing;
using XmlDocFormat.Tests.Shared;

namespace XmlDocFormat.InternalGenerators.Tests;

public sealed class GeneratorOutputWriterTests
{
    [Test]
    public async Task Empty()
    {
        var mappings = new GeneratedSourceMappings();

        const string expected =
            """
            // <auto-generated>
            //     This file has been auto-generated by
            //     GeneratorOutputWriter
            // </auto-generated>

            // The purpose of this file is to show the output of a generator
            // run and construct the generator output expectation in RoseLynn's
            // fasion with GeneratedSourceMappings. The following code might
            // not be perfectly applicable without modifications depending on
            // the test project's structure.
            // The file has been constructed as a file-based program that does
            // not run any actual code, and only expresses the expected
            // generator output.

            #nullable enable
            
            var mappings = new GeneratedSourceMappings
            {
            };
            
            """;

        await AssertSourceMappingsCodeGeneration(mappings, expected);
    }

    [Test]
    public async Task TwoFiles()
    {
        var mappings = new GeneratedSourceMappings
        {
            ["file1.g.cs"] =
                GeneralGeneratorTestHelpers.Utf8CSharpSource(
                    """
                    var x = 1;
                    """),

            ["file2.g.cs"] =
                GeneralGeneratorTestHelpers.Utf8CSharpSource(
                    """
                    var x = 2;
                    """),
        };

        const string expected =
            """"
            // <auto-generated>
            //     This file has been auto-generated by
            //     GeneratorOutputWriter
            // </auto-generated>

            // The purpose of this file is to show the output of a generator
            // run and construct the generator output expectation in RoseLynn's
            // fasion with GeneratedSourceMappings. The following code might
            // not be perfectly applicable without modifications depending on
            // the test project's structure.
            // The file has been constructed as a file-based program that does
            // not run any actual code, and only expresses the expected
            // generator output.

            #nullable enable

            var mappings = new GeneratedSourceMappings
            {
                ["file1.g.cs"] =
                    Utf8CSharpSource(
                        """
                        var x = 1;
                        """),

                ["file2.g.cs"] =
                    Utf8CSharpSource(
                        """
                        var x = 2;
                        """),
            };

            """";

        await AssertSourceMappingsCodeGeneration(mappings, expected);
    }

    [Test]
    public async Task FileWithEndingNewLine()
    {
        var mappings = new GeneratedSourceMappings
        {
            ["new-line-ending-file.g.cs"] =
                GeneralGeneratorTestHelpers.Utf8CSharpSource(
                    """
                    var x = 1;

                    """),
        };

        const string expected =
            """"
            // <auto-generated>
            //     This file has been auto-generated by
            //     GeneratorOutputWriter
            // </auto-generated>

            // The purpose of this file is to show the output of a generator
            // run and construct the generator output expectation in RoseLynn's
            // fasion with GeneratedSourceMappings. The following code might
            // not be perfectly applicable without modifications depending on
            // the test project's structure.
            // The file has been constructed as a file-based program that does
            // not run any actual code, and only expresses the expected
            // generator output.

            #nullable enable

            var mappings = new GeneratedSourceMappings
            {
                ["new-line-ending-file.g.cs"] =
                    Utf8CSharpSource(
                        """
                        var x = 1;

                        """),
            };

            """";

        await AssertSourceMappingsCodeGeneration(mappings, expected);
    }

    private static async Task AssertSourceMappingsCodeGeneration(
        GeneratedSourceMappings mappings,
        [StringSyntax(PredefinedEmbeddedLanguageNames.CSharpTest)]
        string expected)
    {
        var source = GeneratorOutputWriter.GenerateSourceMappingsCode(mappings);
        var normalizedExpected = source.NormalizeNewLines(WhitespaceFacts.CrLf);
        await Assert.That(source).IsEqualTo(normalizedExpected);
    }
}
