name: run-tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Pack XmlDocFormat.InternalGenerators
      run: dotnet pack ./tools/XmlDocFormat.InternalGenerators/XmlDocFormat.InternalGenerators.csproj --configuration Release

    - name: Restore Solution
      run: dotnet restore ./XmlDocFormat.slnx --verbosity detailed

    - name: Build Solution
      run: dotnet build --force --configuration Release

    - name: Run All Tests
      run: dotnet test --solution ./ --no-build --configuration Release
