name: test-tool-executes

on: workflow_dispatch

jobs:
  run:
    runs-on: windows-latest
    steps:
    - name: XmlDocFormat.Cli Install
      run:
        dotnet tool install XmlDocFormat.Cli --tool-path /tmp/xmldocformat.cli

    - name: Run XmlDocFormat.Cli
      run:
        /tmp/xmldocformat.cli/XmlDocFormat --version
